LDAPVerifyServerCert off

<VirtualHost *:443>
SSLEngine on
SSLCertificateFile      /etc/ssl/certs/WebR2.https.crt
SSLCertificateKeyFile   /etc/ssl/private/WebR2.https.key
DocumentRoot /var/www/html/reservator

<Directory /var/www/html/reservator>
	Options Indexes FollowSymLinks
        AllowOverride None
        AuthType Basic
        AuthName "Apache LDAP authentification"
        AuthBasicProvider ldap
        AuthLDAPBindAuthoritative on
        AuthLDAPURL "ldaps://auth2.m2l.fr/OU=People,DC=m2l,DC=fr"
        Require valid-user
	
</Directory>


</VirtualHost>
